version: '2.1'

services:
  database:
    image: postgres:latest
    ports:
    # changed port bc votesnack db is already running on that port
      - "5632:5532"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "localme_dev"
#      POSTGRES_HOST: "database"
#    volumes:
#        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
#        - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
    command: -p 5532
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
          test: ["CMD-SHELL", "pg_isready -U postgres -p 5532"]
          interval: 10s
          timeout: 5s
          retries: 5

  configserver:
    image: localme/configserver:0.0.1-SNAPSHOT
    ports:
       - "8071:8071"
    environment:
    # dont run tests at docker build time, bc at build time cant resolve env vars... -> no test, no query of env var...
      ENCRYPT_KEY: "${ENCRYPT_KEY}"
      GIT_READ_KEY: "${GIT_READ_KEY}"
    networks:
      backend:
        aliases:
          - "configserver"
#    healthcheck:
##              test: ["CMD", "curl", "-f", "configserver:8071/actuator/health"]
#              test: ["CMD-SHELL", "wait-for-it", "configserver:8071"]
#              interval: 10s
#              timeout: 5s
#              retries: 5

  posting-service:
    image: localme/posting-service:0.0.2-SNAPSHOT
#    restart: on-failured
    depends_on:
        database:
          condition: service_healthy
        configserver:
#          condition: service_healthy
          condition: service_started
    ports:
      - "8080:8080"
    networks:
      - backend

  comment-service:
      image: localme/comment-service:0.0.1-SNAPSHOT
      depends_on:
          database:
            condition: service_healthy
          configserver:
  #          condition: service_healthy
            condition: service_started
#      restart: on-failure
      ports:
          - "8081:8080"
      networks:
          - backend
#      command: [ "CMD-SHELL", "wait-for-it", "configserver:8071", "--", "java","-jar","/app.jar" ]
#      command: "bash -c 'wait-for-it configserver:8071 -- java -jar /app.jar'"
#
  local-posting-service:
      image: localme/local-posting-service:0.0.1-SNAPSHOT
      depends_on:
         database:
           condition: service_healthy
         configserver:
  #          condition: service_healthy
           condition: service_started
#      restart: on-failure
      ports:
        - "8082:8080"
      networks:
        - backend
#      command: "wait-for-it configserver:8071 -- java -jar /app.jar"
#      command: [ "CMD-SHELL", "wait-for-it", "configserver:8071", "--", "java","-jar","/app.jar" ]
#      command: "bash -c 'wait-for-it configserver:8071 -- java -jar /app.jar'"

networks:
  backend:
    driver: bridge