POST http://localhost:8080/api/core/posting/create
Content-Type: application/json

{
  "title": "gil",
  "text": "gil is a gil",
  "longitude": 123,
  "latitude": 242,
  "contactable": true
}

#### find all postings with comments
GET http://localhost:8080/api/core/posting/find-with-comments?posting-id=1
Accept: application/json